<base href="<?=base_url();?> ">
<link rel="stylesheet" href="assets_frond/css/bootstrap.css">
<link rel="stylesheet" href="assets_frond/css/animate.css">
<link rel="stylesheet" href="assets_frond/css/swiper-bundle.css">
<link rel="stylesheet" href="assets_frond/css/slick.css">
<link rel="stylesheet" href="assets_frond/css/magnific-popup.css">
<link rel="stylesheet" href="assets_frond/css/font-awesome-pro.css">
<link rel="stylesheet" href="assets_frond/css/flaticon_shofy.css">
<link rel="stylesheet" href="assets_frond/css/spacing.css">
<link rel="stylesheet" href="assets_frond/css/main.css">